name: Create Release with Metadata

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Run script and create release
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (if required)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run the Python script
    - name: Run compile-metadata.py
      run: python compile-metadata.py

    # Step 5: Create release using softprops/action-gh-release
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: store-metadata.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Upload store-metadata.json as an artifact
    - name: Upload Metadata as Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: store-metadata
        path: store-metadata.json
