name: Create Release with Metadata

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Run script and create release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      # Step 4: Run the Python script
      - name: Run compile-metadata.py
        run: python compile-metadata.py


      # Step 8: Upload store-metadata.json as an artifact
      - name: Upload Metadata as Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: store-metadata
          path: store-metadata.json

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "store-metadata.json"
          tag: v1.0.0-${{ github.run_number }}
