name: Create Release with Metadata

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Run script and create release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Run the Python script
      - name: Run compile-metadata.py
        run: python compile-metadata.py

      # Step 4: Create a GitHub release and attach the JSON file
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          files: "store-metadata.json" # Attach the JSON file
          name: Release ${{ github.run_number }}
          generate_release_notes: true
